### ISSUE TITLE
PermissionError / Operation not permitted

### ISSUE THREAD

**Issue by V10lator** [INTI-CMNB/kicad_auto#17]
So I created this simple Dockerfile:
```
FROM ghcr.io/inti-cmnb/kicad7_auto:1.6.3-2_k7.0.9_d12.1

WORKDIR /
```
Then executed `docker build . -t test_builder` and finally `docker run --rm -v ${PWD}:/project test_builder kibot --quick-start --dry` but the last command errors out:
```
Traceback (most recent call last):
  File "/usr/bin/kibot", line 33, in <module>
    sys.exit(load_entry_point('kibot==1.6.3', 'console_scripts', 'kibot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/kibot/__main__.py", line 470, in main
    generate_examples(args.start, args.dry, args.type)
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 1048, in generate_examples
    for f in _walk(start_dir, 6):
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 981, in _walk
    yield from _walk(entry.path, depth)
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 981, in _walk
    yield from _walk(entry.path, depth)
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 981, in _walk
    yield from _walk(entry.path, depth)
  [Previous line repeated 2 more times]
  File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 980, in _walk
    if entry.is_dir() and depth > 0:
       ^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: './proc/self/fd/5/map_files/400000-41f000'
```

**Comment by set-soft** [comment]
Hi @V10lator !

You are starting *quick-start* from a directory that isn't fully searchable. Don't use / as wording directory, not even the root user will be able to read every single file.
